name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f
          
    - name: Build the Docker image
      run: |
          docker build . --file Dockerfile --tag hello-algo:$(date +%s)
          docker ps images
          docker save hello-algo -o hello-algo-amd64.tar

    - name: Compress the TAR files
      run: tar -czf hello-algo.tar.gz *-amd64.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: hello-algo.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天      
        
    - name: Clean up intermediate files
      run: |
        rm *-amd64.tar        
